import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientFlowValue
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientFlowContraction
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientFlowPL
import AutoSamplingTheory.TechnicalLemmas.Analysis.StrongConvexPLPullback
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexGradientGapSharpness
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentSharpness
import AutoSamplingTheory.TechnicalLemmas.Analysis.QuadraticGradientDescent
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentOptimalStep
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentStationarity
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentBasic
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentPL
import AutoSamplingTheory.TechnicalLemmas.Analysis.Calculus
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexAEDifferentiable
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexSubgradient
import AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicCostExpectation
import AutoSamplingTheory.TechnicalLemmas.Analysis.CyclicQuadraticCost
import AutoSamplingTheory.TechnicalLemmas.Analysis.Integrability
import AutoSamplingTheory.TechnicalLemmas.Analysis.LeftLebesgueAverage
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCyclicMonotonicity
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCycleNeighborhood
import AutoSamplingTheory.TechnicalLemmas.Analysis.PairingCycleQuantitativeNeighborhood
import AutoSamplingTheory.TechnicalLemmas.Analysis.PermutedQuadraticCost
import AutoSamplingTheory.TechnicalLemmas.Analysis.PrefixIntegral
import AutoSamplingTheory.TechnicalLemmas.Analysis.StrongConvexFirstOrder
import AutoSamplingTheory.TechnicalLemmas.Analysis.StrongConvexGradientConverse
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexityC1
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexityC2
import AutoSamplingTheory.TechnicalLemmas.Analysis.SmoothnessEquivalences
import AutoSamplingTheory.TechnicalLemmas.Analysis.ConvexSmoothGradient
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentContraction
import AutoSamplingTheory.TechnicalLemmas.Analysis.GradientDescentValue

/-!
# Analysis technical lemma arsenal

Parent import surface for reusable analysis lemmas.
-/
