import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.Generator
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.LogSobolev
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.Poincare
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.SemigroupDecay
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedBochner
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedGradient
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedGradientWeak
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedGradientDistribution
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedResolvent
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.WeightedLocalL2
import AutoSamplingTheory.TechnicalLemmas.FunctionalInequalities.ClosedGraphResolvent

/-!
# Functional-inequality technical lemma arsenal

Parent import surface for Poincare, log-Sobolev, Fisher-information, and
functional-inequality-to-semigroup-decay reusable leaves.
-/
