import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalDirichletFisher
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalKLDissipation
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.CanonicalRelativeFisher
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.DonskerVaradhan
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.FisherTransport
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.GeodesicFisherTransport
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.KLDensity
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.RNLogRatio
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.TiltedLogRatio
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.TiltedKL
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.QuadraticTiltFisher
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.RelativeFisher
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.Renyi
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergence
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceGradient
import AutoSamplingTheory.TechnicalLemmas.InformationTheory.SimultaneousFDivergenceIntegral

/-!
# Information-theoretic technical lemma arsenal

Parent import surface for KL/DV/Renyi/relative-Fisher/Fisher-transport/entropy-style reusable leaves.
-/
