import AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementJacobianSpectral

#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementJacobianSpectral.det_affineIdentity_eq_prod_eigenvalues
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementJacobianSpectral.spectrumLogDet_affineIdentity_eigenvalues_eq_log_det
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementJacobianSpectral.log_det_affineIdentity_ge
#check AutoSamplingTheory.TechnicalLemmas.Measure.DisplacementJacobianSpectral.neg_log_det_affineIdentity_le
