import AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence

#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence.probabilityCouplingSet_nonempty
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence.quadraticObjective
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence.exists_isMinOn_quadraticObjective
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence.exists_quadraticOptimalCoupling_probabilityMeasure
#check AutoSamplingTheory.TechnicalLemmas.Measure.QuadraticOptimalCouplingExistence.exists_quadraticOptimalCoupling
