import AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.WeakAdjointDensity

#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.WeakAdjointDensity.WeakAdjointDensityEquationAt
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.WeakAdjointDensity.time_pairing_integrable
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.WeakAdjointDensity.generator_pairing_integrable
#check AutoSamplingTheory.TechnicalLemmas.StochasticProcesses.WeakAdjointDensity.pairing_eq
