import AutoSamplingTheory.ExampleCases.SampleWiki
import AutoSamplingTheory.ExampleCases.ProximalBPS.GaussianReflection
import AutoSamplingTheory.ExampleCases.ProximalBPS.GaussianAugmentation
import AutoSamplingTheory.ExampleCases.ProximalBPS.GibbsAugmentation
import AutoSamplingTheory.ExampleCases.ProximalBPS.ReflectionL2
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalScore
import AutoSamplingTheory.ExampleCases.ProximalBPS.MacroscopicRepresentative
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalScoreDomain
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalBochner
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalGradient
import AutoSamplingTheory.ExampleCases.ProximalBPS.ConditionalResolvent
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveCondition
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RGOClosure
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RGOCalculus
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveVariance
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RecursiveDepth
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.LogarithmicDepth
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.Truncation
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianPowerMoment
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianMixture
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ProxyReverseTransport
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianKL
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.RGOBackward
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TwoNoiseRGO
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.AdaptiveCenterRGO
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.AdaptiveKLError
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.StateDependentRGO
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.FiniteRGOProgram
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.StoppedRGODepth
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.FiniteRGOKLError
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianRGOErrorBudget
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.StoppedGaussianRGOError
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.PoissonRejection
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.PoissonQueryTail
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GaussianArcLaw
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.SmoothGradientArcMoment
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.SmoothGradientArcClipping
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GradientArcMean
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.IdealRGOIdentification
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedMeanExponential
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedRenyiComparison
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalSamplerAccuracyCost
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalReferenceGradientDescent
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ApproximateInitialGradientMoment
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.JointReferenceGradientDescent
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.NormalizedReferenceCall
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ReferenceCarryingKernel
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ReferenceCarryingCost
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.TerminalFORSKernel
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.EnhancedTerminalExecution
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ObservationConditionalKernel
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.EnhancedKLOneStep
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.EnhancedFiniteOutputKL
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ProximalGaussianEstimator
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.GibbsPositionMoment
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ProximalEstimatorLipschitz
import AutoSamplingTheory.ExampleCases.SmoothedPicardHMC.ClippedGradientProgram

/-!
# ASTIS example cases

This namespace is the public Lean entry point for externally sourced worked
examples that ASTIS turns into source-pinned theorem targets and then absorbs
into the reusable sampling-theory dependency graph.
-/
